module.exports = {
  id: "perfilCompleto_bioceli",
  formFile: "perfilcompleto_bioceli_felino.html",
  templateFile: "perfilcompleto_bioceli_felino_template.html",
  type: "table",

  meta: {
    title: "Perfil Bioquímico Completo",
    headerTitle: ["Resultados de laboratorio", "Perfil Bioquímico Completo"],
    formTitle: "RESULTADOS DE LABORATORIO<br />PERFIL BIOQUÍMICO COMPLETO",
    maquilado:
      "Laboratorio BIO-C-ELI. Av. Nicolas Bravo No.22 entre Abasolo e Independencia, CP. 29960, Palenque, Chiapas",
  },

  sections: [
    {
      title: "Perfil Bioquímico",
      fields: [
        "alb",
        "tgo",
        "tgp",
        "fosfatasa_alcalina",
        "gamma_glutamil",
        "proteinas_totales",
        "globulina",
        "rel_ag",
        "bilirrubina_directa",
        "bilirrubina_total",
        "bilirrubina_indirecta",
        "dhl",
        "amilasa",
        "lipasa",
        "glucosa",
        "nitrogeno_ureico",
        "creatinina",
        "urea",
        "acido_urico",
        "colesterol",
        "trigliceridos",
      ],
    },
  ],

  fields: [
    {
      id: "alb",
      templateField: "alb",
      label: "Albúmina (ALB)",
      min: "2.60",
      max: "4.40",
      unit: "g/dL",
    },
    {
      id: "tgo",
      templateField: "tgo",
      label: "TGO",
      min: "14.00",
      max: "42.00",
      unit: "g/dL",
    },
    {
      id: "tgp",
      templateField: "tgp",
      label: "TGP",
      min: "15.00",
      max: "52.00",
      unit: "U/L",
    },
    {
      id: "fosfatasa_alcalina",
      templateField: "fosfatasa_alcalina",
      label: "Fosfatasa Alcalina",
      min: "23.00",
      max: "212.00",
      unit: "U/L",
    },
    {
      id: "gamma_glutamil",
      templateField: "gamma_glutamil",
      label: "Gamma Glutamil",
      min: "0.0",
      max: "12.00",
      unit: "U/L",
    },
    {
      id: "proteinas_totales",
      templateField: "proteinas_totales",
      label: "Proteínas Totales",
      min: "5.40",
      max: "7.20",
      unit: "g/dL",
    },
    {
      id: "globulina",
      templateField: "globulina",
      label: "Globulina",
      min: "2.70",
      max: "4.40",
      unit: "g/dL",
    },
    {
      id: "rel_ag",
      templateField: "rel_ag",
      label: "Relación A/G",
      min: "0.60",
      max: "1.10",
      unit: "",
    },
    {
      id: "bilirrubina_directa",
      templateField: "bilirrubina_directa",
      label: "Bilirrubina Directa",
      min: "0.00",
      max: "0.25",
      unit: "mg/dL",
    },
    {
      id: "bilirrubina_total",
      templateField: "bilirrubina_total",
      label: "Bilirrubina Total",
      min: "0.00",
      max: "0.80",
      unit: "mg/dL",
    },
    {
      id: "bilirrubina_indirecta",
      templateField: "bilirrubina_indirecta",
      label: "Bilirrubina Indirecta",
      min: "0.00",
      max: "0.40",
      unit: "mg/dL",
    },
    {
      id: "dhl",
      templateField: "dhl",
      label: "Deshidrogenasa Láctica (DHL)",
      min: "",
      max: "",
      unit: "",
    },
    {
      id: "amilasa",
      templateField: "amilasa",
      label: "Amilasa",
      min: "0.00",
      max: "1500.00",
      unit: "u/L",
    },
    {
      id: "lipasa",
      templateField: "lipasa",
      label: "Lipasa",
      min: "0.00",
      max: "240.00",
      unit: "u/L",
    },
    {
      id: "glucosa",
      templateField: "glucosa",
      label: "Glucosa",
      min: "70.00",
      max: "105.00",
      unit: "mg/dL",
    },
    {
      id: "nitrogeno_ureico",
      templateField: "nitrogeno_ureico",
      label: "Nitrógeno Uréico",
      min: "4.50",
      max: "30.50",
      unit: "mg/dL",
    },
    {
      id: "creatinina",
      templateField: "creatinina",
      label: "Creatinina",
      min: "0.60",
      max: "1.40",
      unit: "mg/dL",
    },
    {
      id: "urea",
      templateField: "urea",
      label: "Urea",
      min: "20.00",
      max: "50.00",
      unit: "mg/dL",
    },
    {
      id: "acido_urico",
      templateField: "acido_urico",
      label: "Ácido Úrico",
      min: "0.00",
      max: "2.00",
      unit: "mg/dL",
    },
    {
      id: "colesterol",
      templateField: "colesterol",
      label: "Colesterol",
      min: "135.00",
      max: "260.00",
      unit: "mg/dL",
    },
    {
      id: "trigliceridos",
      templateField: "trigliceridos",
      label: "Triglicéridos",
      min: "25.00",
      max: "120.00",
      unit: "mg/dL",
    },
  ],
};
