module.exports = {
  id: "perfilCompleto_vetpec",
  formFile: "perfilcompleto_vetpec_canino.html",
  templateFile: "perfilcompleto_vetpec_canino_template.html",
  type: "table",

  meta: {
    title: "Perfil Bioquímico Completo",
    headerTitle: ["Resultados de laboratorio", "Perfil Bioquímico Completo"],
    formTitle: "RESULTADOS DE LABORATORIO<br />PERFIL BIOQUÍMICO COMPLETO",
    maquilado:
      "Clinica Veterinaria PEC. Prol. Aladama esquina Revolución, Col. Centro CP. 29960, Palenque, Chiapas",
  },

  sections: [
    {
      title: "Perfil Bioquímico",
      fields: [
        "tp",
        "alb",
        "glob",
        "a_g",
        "alt",
        "ast",
        "ast_alt",
        "alp",
        "ggt",
        "tbil",
        "tba",
        "amy",
        "lipa-d",
        "bun",
        "crea",
        "bun_crea",
        "ck",
        "ldh",
        "glu",
        "tc",
        "tg",
        "ca",
        "phos",
        "caxp",
        "mg",
        "na",
        "k",
        "na_k",
        "cl",
      ],
    },
  ],

  fields: [
    {
      id: "tp",
      templateField: "tp",
      label: "Proteína TP",
      min: "52.00",
      max: "82.00",
      unit: "g/L",
    },
    {
      id: "alb",
      templateField: "alb",
      label: "Proteína ALB",
      min: "21.00",
      max: "40.00",
      unit: "g/L",
    },
    {
      id: "glob",
      templateField: "glob",
      label: "Proteína GLOB",
      min: "25.40",
      max: "52.00",
      unit: "g/L",
    },
    {
      id: "a_g",
      templateField: "a_g",
      label: "Proteína A/G",
      min: "",
      max: "",
      unit: "",
    },
    {
      id: "alt",
      templateField: "alt",
      label: "Hígado y vesícula biliar ALT",
      min: "10.10",
      max: "100.30",
      unit: "U/L",
    },
    {
      id: "ast",
      templateField: "ast",
      label: "Hígado y vesícula biliar AST",
      min: "0.00",
      max: "51.70",
      unit: "U/L",
    },
    {
      id: "ast_alt",
      templateField: "ast_alt",
      label: "Hígado y vesícula biliar AST/ALT",
      min: "",
      max: "",
      unit: "",
    },
    {
      id: "alp",
      templateField: "alp",
      label: "Hígado y vesícula biliar ALP",
      min: "15.50",
      max: "212.00",
      unit: "U/L",
    },
    {
      id: "ggt",
      templateField: "ggt",
      label: "Hígado y vesícula biliar GGT",
      min: "0.00",
      max: "15.90",
      unit: "umol/L",
    },
    {
      id: "tbil",
      templateField: "tbil",
      label: "Hígado y vesícula biliar TBIL",
      min: "0.00",
      max: "15.00",
      unit: "umol/L",
    },
    {
      id: "tba",
      templateField: "tba",
      label: "Hígado y vesícula biliar TBA",
      min: "0.00",
      max: "30.00",
      unit: "umol/L",
    },
    {
      id: "amy",
      templateField: "amy",
      label: "Páncreas AMY",
      min: "397.70",
      max: "1285.10",
      unit: "U/L",
    },
    {
      id: "lipa-d",
      templateField: "lipa-d",
      label: "Páncreas LIPA-D",
      min: "0.00",
      max: "100.00",
      unit: "U/L",
    },
    {
      id: "bun",
      templateField: "bun",
      label: "Riñones BUN",
      min: "2.50",
      max: "9.77",
      unit: "mmol/L",
    },
    {
      id: "crea",
      templateField: "crea",
      label: "Riñones CREA",
      min: "20.00",
      max: "123.70",
      unit: "umol/L",
    },
    {
      id: "bun_crea",
      templateField: "bun_crea",
      label: "Riñones BUN/CREA",
      min: "",
      max: "",
      unit: "",
    },
    {
      id: "ck",
      templateField: "ck",
      label: "Cardiovasc./Músculo CK",
      min: "66.40",
      max: "257.50",
      unit: "U/L",
    },
    {
      id: "ldh",
      templateField: "ldh",
      label: "Cardiovasc./Músculo LDH",
      min: "0.00",
      max: "143.60",
      unit: "U/L",
    },
    {
      id: "glu",
      templateField: "glu",
      label: "Metabolismo energético GLU",
      min: "3.80",
      max: "7.50",
      unit: "mmol/L",
    },
    {
      id: "tc",
      templateField: "tc",
      label: "Metabolismo energético TC",
      min: "2.67",
      max: "8.38",
      unit: "mmol/L",
    },
    {
      id: "tg",
      templateField: "tg",
      label: "Metabolismo energético TG",
      min: "0.10",
      max: "1.30",
      unit: "mmol/L",
    },
    {
      id: "ca",
      templateField: "ca",
      label: "Minerales Ca",
      min: "2.10",
      max: "2.97",
      unit: "mmol/L",
    },
    {
      id: "phos",
      templateField: "phos",
      label: "Minerales PHOS",
      min: "0.70",
      max: "2.20",
      unit: "mmol/L",
    },
    {
      id: "caxp",
      templateField: "caxp",
      label: "Minerales CaxP",
      min: "",
      max: "",
      unit: "(mmol/L)<sup>2</sup>",
    },
    {
      id: "mg",
      templateField: "mg",
      label: "Minerales Mg",
      min: "0.53",
      max: "1.06",
      unit: "mmol/L",
    },
    {
      id: "na",
      templateField: "na",
      label: "Electrolitos Na+",
      min: "138.00",
      max: "160.00",
      unit: "mmol/L",
    },
    {
      id: "k",
      templateField: "k",
      label: "Electrolitos K+",
      min: "3.50",
      max: "5.90",
      unit: "mmol/L",
    },
    {
      id: "na_k",
      templateField: "na_k",
      label: "Electrolitos Na/K",
      min: "",
      max: "",
      unit: "",
    },
    {
      id: "cl",
      templateField: "cl",
      label: "Electrolitos CL-",
      min: "100.7",
      max: "125.00",
      unit: "mmol/L",
    },
  ],
};
