module.exports = {
  id: "perfilCompleto_vetpec",
  formFile: "perfilcompleto_vetpec_felino.html",
  templateFile: "perfilcompleto_vetpec_felino_template.html",
  type: "table",

  meta: {
    title: "Perfil Bioquímico Completo",
    headerTitle: ["Resultados de laboratorio", "Perfil Bioquímico Completo"],
    formTitle: "RESULTADOS DE LABORATORIO<br />PERFIL BIOQUÍMICO COMPLETO",
    maquilado:
      "Clinica Veterinaria PEC. Prol. Aladama esquina Revolución, Col. Centro CP. 29960, Palenque, Chiapas",
    extraStyles: `
    .results-table { font-size: 14px; margin: 4px auto; }
    `,
  },

  sections: [
    {
      title: "Perfil Bioquímico",
      fields: [
        "tp",
        "alb",
        "glob",
        "a_g",
        "alt",
        "ast",
        "ast_alt",
        "alp",
        "ggt",
        "tbil",
        "tba",
        "amy",
        "lipa-d",
        "bun",
        "crea",
        "bun_crea",
        "ck",
        "ldh",
        "glu",
        "tc",
        "tg",
        "ca",
        "phos",
        "caxp",
        "mg",
        "na",
        "k",
        "na_k",
        "cl",
      ],
    },
  ],

  fields: [
    {
      id: "tp",
      templateField: "tp",
      label: "Proteína TP",
      min: "56.50",
      max: "88.50",
      unit: "g/L",
    },
    {
      id: "alb",
      templateField: "alb",
      label: "Proteína ALB",
      min: "22.00",
      max: "40.00",
      unit: "g/L",
    },
    {
      id: "glob",
      templateField: "glob",
      label: "Proteína GLOB",
      min: "28.20",
      max: "55.80",
      unit: "g/L",
    },
    {
      id: "a_g",
      templateField: "a_g",
      label: "Proteína A/G",
      min: "",
      max: "",
      unit: "",
    },
    {
      id: "alt",
      templateField: "alt",
      label: "Hígado y vesícula biliar ALT",
      min: "12.00",
      max: "149.20",
      unit: "U/L",
    },
    {
      id: "ast",
      templateField: "ast",
      label: "Hígado y vesícula biliar AST",
      min: "0.00",
      max: "60.00",
      unit: "U/L",
    },
    {
      id: "ast_alt",
      templateField: "ast_alt",
      label: "Hígado y vesícula biliar AST/ALT",
      min: "",
      max: "",
      unit: "",
    },
    {
      id: "alp",
      templateField: "alp",
      label: "Hígado y vesícula biliar ALP",
      min: "8.70",
      max: "110.90",
      unit: "U/L",
    },
    {
      id: "ggt",
      templateField: "ggt",
      label: "Hígado y vesícula biliar GGT",
      min: "0.00",
      max: "8.20",
      unit: "umol/L",
    },
    {
      id: "tbil",
      templateField: "tbil",
      label: "Hígado y vesícula biliar TBIL",
      min: "0.00",
      max: "15.00",
      unit: "umol/L",
    },
    {
      id: "tba",
      templateField: "tba",
      label: "Hígado y vesícula biliar TBA",
      min: "0.00",
      max: "20.00",
      unit: "umol/L",
    },
    {
      id: "amy",
      templateField: "amy",
      label: "Páncreas AMY",
      min: "555.60",
      max: "1940.00",
      unit: "U/L",
    },
    {
      id: "lipa-d",
      templateField: "lipa-d",
      label: "Páncreas LIPA-D",
      min: "0.00",
      max: "20.00",
      unit: "U/L",
    },
    {
      id: "bun",
      templateField: "bun",
      label: "Riñones BUN",
      min: "4.55",
      max: "11.41",
      unit: "mmol/L",
    },
    {
      id: "crea",
      templateField: "crea",
      label: "Riñones CREA",
      min: "28.00",
      max: "180.00",
      unit: "umol/L",
    },
    {
      id: "bun_crea",
      templateField: "bun_crea",
      label: "Riñones BUN/CREA",
      min: "",
      max: "",
      unit: "",
    },
    {
      id: "ck",
      templateField: "ck",
      label: "Cardiovasc./Músculo CK",
      min: "66.10",
      max: "530.90",
      unit: "U/L",
    },
    {
      id: "ldh",
      templateField: "ldh",
      label: "Cardiovasc./Músculo LDH",
      min: "0.00",
      max: "334.20",
      unit: "U/L",
    },
    {
      id: "glu",
      templateField: "glu",
      label: "Metabolismo energético GLU",
      min: "3.39",
      max: "8.39",
      unit: "mmol/L",
    },
    {
      id: "tc",
      templateField: "tc",
      label: "Metabolismo energético TC",
      min: "1.87",
      max: "5.84",
      unit: "mmol/L",
    },
    {
      id: "tg",
      templateField: "tg",
      label: "Metabolismo energético TG",
      min: "0.10",
      max: "1.30",
      unit: "mmol/L",
    },
    {
      id: "ca",
      templateField: "ca",
      label: "Minerales Ca",
      min: "2.10",
      max: "2.79",
      unit: "mmol/L",
    },
    {
      id: "phos",
      templateField: "phos",
      label: "Minerales PHOS",
      min: "0.80",
      max: "2.72",
      unit: "mmol/L",
    },
    {
      id: "caxp",
      templateField: "caxp",
      label: "Minerales CaxP",
      min: "",
      max: "",
      unit: "(mmol/L)<sup>2</sup>",
    },
    {
      id: "mg",
      templateField: "mg",
      label: "Minerales Mg",
      min: "0.66",
      max: "1.22",
      unit: "mmol/L",
    },
    {
      id: "na",
      templateField: "na",
      label: "Electrolitos Na+",
      min: "141.00",
      max: "166.00",
      unit: "mmol/L",
    },
    {
      id: "k",
      templateField: "k",
      label: "Electrolitos K+",
      min: "3.50",
      max: "5.90",
      unit: "mmol/L",
    },
    {
      id: "na_k",
      templateField: "na_k",
      label: "Electrolitos Na/K",
      min: "",
      max: "",
      unit: "",
    },
    {
      id: "cl",
      templateField: "cl",
      label: "Electrolitos CL-",
      min: "102.40",
      max: "129.00",
      unit: "mmol/L",
    },
  ],
};
